bug: 55117,55119
Initial limited JSON with JAXB support.
Also reworks initial fix planned for Bug 55119 - faster
Element <-> JAXB processing.

Element.java and JaxbUtil.java updated to allow 
JSONElement <-> JAXB conversions. 3 different variants which convert
an element to Jaxb are still present in JaxbUtil.java for testing
and performance analysis - a winner needs to be chosen.
Testing with a modified ExportContacts.java server handler exposed a worrying
issue with the initial proposed fix to 55117.
zmsoap -z -m user1 -v ExportContactsRequest @ct=csv
always appeared to work, however,
zmsoap --json -z -m user1 -v ExportContactsRequest @ct=csv
would sometimes throw an exception:
  javax.xml.bind.UnmarshalException: Namespace URIs and local
       names to the unmarshaller needs to be interned.
Tried updating Element.toXml() to intern element names and attribute
names but that didn't seem to make a difference.
Decided to use w3c Dom as the XML representation instead of dom4j
and have not seen any issues with that in testing so far.  Also appears to
be marginally faster.

This implementation of Element <-> Jaxb handles Xml that matches the rules
encoded in the Jaxb classes but does NOT handle the more relaxed forms 
of Xml currently supported by Zimbra - for instance where attributes
are supplied as elements instead.

http://bugzilla.zimbra.com/show_bug.cgi?id=55117
http://bugzilla.zimbra.com/show_bug.cgi?id=55119