Integrated change 282065 from HELIX to main.
------------

Change 282065 by bburtin@bburtin-ubuntu-helix on 2011/03/16 15:40:56

	bug: 58032 - Servlet initialization fails because JUnit is not available

	Added exception handling for NoClassDefFoundError around
	callsites to ZimbraSuite.addTest().


Affected files ...

... //depot/zimbra/HELIX/ZimbraAdminVersionCheck/src/java/com/zimbra/cs/versioncheck/VersionCheckExtension.java#3 edit
... //depot/zimbra/HELIX/ZimbraBackup/src/java/com/zimbra/cs/backup/BackupExtension.java#2 edit
... //depot/zimbra/HELIX/ZimbraConvertd/src/java/com/zimbra/cs/convert/ConverterExtension.java#2 edit
... //depot/zimbra/HELIX/ZimbraHSM/src/java/com/zimbra/cs/hsm/HsmInitializer.java#3 edit

http://bugzilla.zimbra.com/show_bug.cgi?id=58032