Integrate change 326641, 326642, and 326646 from ZDESKTOP-712        bug: 63640
       Only invoke IMPersona.deleteIMPersona if IM is enabled. This is 
       somewhat redundant since same check occurs in 
       IMPersona.deleteIMPersona, but it avoid NoClassDefFoundError which 
       occurs if IM jars are not on classpath.

       Remove indirect call to ZimbraIM which occurs during account 
       reset/mailbox delete.

http://bugzilla.zimbra.com/show_bug.cgi?id=63640