http://bugzilla.zimbra.com/show_bug.cgi?id=10982 bug: 10982
Change 32561 broke restore, throwing this exception:

com.zimbra.cs.service.ServiceException: system failure: cannot fetch Connection outside transaction
        at com.zimbra.cs.service.ServiceException.FAILURE(ServiceException.java:174)
        at com.zimbra.cs.mailbox.Mailbox.getOperationConnection(Mailbox.java:708)
        at com.zimbra.cs.db.DbMailbox.dropMailboxFromGroup(DbMailbox.java:278)
        at com.zimbra.cs.db.DbMailbox.clearMailboxContent(DbMailbox.java:299)
        at com.zimbra.cs.backup.RestoreAccountSession.loadTablesFromLocalFile(RestoreAccountSession.java:382)
        at com.zimbra.cs.backup.FileBackupTarget$RestoreAcctSession.loadTables(FileBackupTarget.java:1318)
        at com.zimbra.cs.backup.RestoreAccountSession.startRestore(RestoreAccountSession.java:180)
        at com.zimbra.cs.backup.FileBackupTarget.restore(FileBackupTarget.java:347)
        at com.zimbra.cs.backup.BackupManager.restore(BackupManager.java:353)
        at com.zimbra.cs.service.backup.Restore.handle(Restore.java:123)
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:262)

This putback fixes that problem.