Integrated change 281559 from HELIX to main.
----------------

Change 281559 by bburtin@bburtin-ubuntu-helix on 2011/03/14 16:44:23

	bug: 57222 - SendMsgRequest: uploaded file not on disk

	If an Upload references a file that's been deleted, log
	a better error message when the caller attempts to
	get the content:

	Caused by: com.zimbra.cs.mailbox.MailSender$SafeSendFailedException: MESSAGE_NOT_DELIVERED; chained exception is:
		java.io.IOException: Cannot get content for upload 89fc7f63-40b6-4afb-ba33-0a02c3b75104:ddc5cafe-70c7-4061-a799-0ac6080fe461 because it was deleted.


Affected files ...

... //depot/zimbra/HELIX/ZimbraServer/src/java/com/zimbra/cs/service/FileUploadServlet.java#5 edit
... //depot/zimbra/HELIX/ZimbraServer/src/java/com/zimbra/qa/unittest/TestSendAndReceive.java#6 edit

http://bugzilla.zimbra.com/show_bug.cgi?id=57222